apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
  - host: helloworldwebapp-deployment.io   
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworldwebapp-service
            port:
              number: 80